### ISSUE TITLE
Is the server still active?

### ISSUE THREAD

**Issue by MichaelGoulding** [Jason-Bloomer/DUOpenMarket#2]
I'm just getting (500) Internal Server Error

**Comment by Jason-Bloomer** [comment]
I have not pushed the post-launch client update yet. It's coming, I promise.

A lot was changed during the game's launch, including ALL market ID's, so nothing will work until a client update is posted. If you try and use an old version of the client meantime, you'll simply get no data back from the server, or an occasional 500 error. (because the server doesnt actually have any data on it right now, and if it did you couldn't pull it because it's all referencing the wrong market ID's)

I am hoping to push the post-launch update this week or next if time and RL allows for it.
