### ISSUE TITLE
Sorting feature does not sort price in proper order

### ISSUE THREAD

**Issue by WarBringereq** [Jason-Bloomer/DUOpenMarket#4]
Sorting on the buy and sell orders table does not sort in order of value.  it sorts by the first number of the value.   so 1000 is before 25 and 200 and 300 instead of actual value order.

**Comment by Jason-Bloomer** [comment]
The sorting function can be a little tricky - are you certain you're using it correctly?

It sorts based off of the last _column_ clicked in the associated grid. (Row doesn't matter)
The header of the column (the row at the very top with the names of each column) should be highlighted blue to show which one is selected.

If I click the price column and then click sort, it seems to work fine in most cases for me. Sometimes when there is a lot of orders for a single item (like for T1 ores) it can get a little confused, but otherwise I am not seeing this behavior.

Likewise sorting by quantities seems to work fine.

Clicking the Market, Expiration, or Item name columns, should perform an alphabetic sort on whichever column was clicked.
Consequentially, clicking no column at all, will often yield the behavior you are describing.

Do keep in mind that every time you click sort, you will again need to click a column to sort by, and it doesn't do reverse-order.

**Comment by Jason-Bloomer** [comment]
Any updates here? Did the steps I provided assist with the problem, or are you still encountering the issue?

**Comment by WarBringereq** [comment]
sorry been at work alot ... will check it soon
    On Sunday, November 13, 2022 at 04:10:06 PM EST, Jason Bloomer ***@***.***> wrote:  
 
 


Any updates here? Did the steps I provided assist with the problem, or are you still encountering the issue?

**Comment by Sethcran** [comment]
I can confirm the original report. Sorting by price or quantity does a lex sort rather than a number sort.

So the following numbers: 100, 11, 200 display in that order, rather than the exxpected: 11, 100, 200.

**Comment by Jason-Bloomer** [comment]
Please verify that you are following the steps I have outlined in my comment pertaining to use of the sorting feature.
If you are following those steps, and things still aren't being sorted correctly, could you please provide a screenshot of this occurring, as well as the item you were sorting orders for when this occurred?
This is not the behaviour I am seeing when following the steps outlined in my comment, as mentioned.

A screenshot of everything working fine on my end. Buy orders sorted by price, Sell orders sorted by quantity, looks good to me.
![image](https://user-images.githubusercontent.com/86666099/202852342-72646035-8668-4d3e-9d15-2e38abd944a0.png)

**Comment by Sethcran** [comment]
I agree that it works per your directions, but I don't think it's necessarily intuitive.

Specifically, normal expectation would be that clicking the price column sorts that column numerically. It does sort, which makes the sort button not obvious that it does anything.

So I guess I would consider this to be a workaround, and that's fine, but would suggest overloading the sort functionality on column click for price/quantity to perform the action that is done on the sort button click, and then remove the sort button entirely.

**Comment by Jason-Bloomer** [comment]
I agree Sethcran, and I appreciate the feedback. It was a temporary workaround but the time has come to do this properly.

I've just pushed out a series of updates which should address the points you've mentioned here. Sorting should now behave a bit more like you would expect it to.
